version: '3.3'
services:
  beforianos-postgres:
    image: postgres
    container_name: beforianos-postgres
    environment:
      - POSTGRES_USER=beforianos
      - POSTGRES_PASSWORD=beforianos
      - POSTGRES_DB=beforianos
    ports:
      - '22201:5432'
    networks:
      - beforianos-network

  beforianos-redis:
    image: bitnami/redis
    container_name: beforianos-redis
    environment:
      - REDIS_PASSWORD=beforianos
    ports:
      - '22202:6379'
    networks:
      - beforianos-network

networks:
  beforianos-network:
    driver: bridge
